- id: american-eg-ie
  name: US English requires a comma after "e.g." and "i.e."
  description: US English requires a comma after "e.g." and "i.e."
  entry: "((e\\.g\\.)|(i\\.e\\.))[^,]"
  language: pygrep
  types: [file, tex]
  minimum_pre_commit_version: "2.8.0"
- id: cleveref-capitalization
  name: Ensure the correct usage of \cref
  description: Ensure that \Cref at a sentence start is capitalized and nowhere else in the sentence.
  entry: |
    (?x)
    ^(
      (?# Consume leading whitespace )
      \s*

      (?# Warn if a lowercase command is used at the beginning of a line, modulo whitespace )
      \\(?:cref|crefrange|cpageref|cpagerefrange|namecref|namecrefs)\b
      |
      (?:
        (?# Do not match if the cref is part of a comment )
        [^%\s][^%]*
        \\(?:Cref|Crefrange|Cpageref|Cpagerefrange|nameCref|nameCrefs)\b
      )
    ).*$
  language: pygrep
  types: [file, tex]
  minimum_pre_commit_version: "2.8.0"
- id: cispa-syssec-forbidden-words
  name: Forbidden words for CISPA SysSec
  entry: "(?i)blacklist|whitelist"
  language: pygrep
  types: [file, tex]
  minimum_pre_commit_version: "2.8.0"
- id: consistent-spelling
  name: Ensure consistency between different spelling variants
  description: Ensure that all variants (specified by regex) are written the same way.
  entry: consistent_spelling
  language: python
  types: [file, tex]
  minimum_pre_commit_version: "2.8.0"
  require_serial: true
  language_version: python3
- id: csquotes
  name: All quotation marks should use csquotes
  description: Ensure the use of LaTeX csquotes and prohibits manual quotation marks.
  entry: "``.*''|''.*''"
  language: pygrep
  types: [file, tex]
  minimum_pre_commit_version: "2.8.0"
- id: ensure-labels-for-sections
  name: Ensure each section has a matching label
  entry: ensure-labels
  language: rust
  types: [file, tex]
  minimum_pre_commit_version: "2.8.0"
- id: no-space-in-cite
  name: "Ensure there are no whitespace characters in the \\cite command"
  entry: '\\cite\{([^\}]*\s)+[^\}]*\}'
  language: pygrep
  types: [file, tex]
  minimum_pre_commit_version: "2.8.0"
- id: sort-bib
  name: Sort bibliography files
  description: Ensure bibliography files are sorted alphabetically.
  entry: sort_bib
  language: python
  types: [file, bib]
  minimum_pre_commit_version: "2.8.0"
  require_serial: true
  language_version: python3
  additional_dependencies: [pybtex]
- id: tilde-cite
  name: Each \cite needs a ~
  description: Line breaks should never occur before the citation, thus they need to be protected with the ~.
  entry: "[^~]\\\\cite\\b"
  language: pygrep
  types: [file, tex]
  minimum_pre_commit_version: "2.8.0"
- id: unique-labels
  name: Ensure each label is only defined once.
  entry: unique_labels
  language: python
  types: [file, tex]
  minimum_pre_commit_version: "2.8.0"
  require_serial: true
  language_version: python3
